// English + Japanese wording (approved). {name} marks a value filled in by the page.
// To fix a wording: change the second text of that line. The English text is shown first, the Japanese under it.
export const S = {
  // ---- room browser / create / join
  title:        ["Learn Live With Friends", "ともだちと ラーンライブ"],
  nickname:     ["Your nickname (up to 20 characters)", "ニックネーム（20文字まで）"],
  rooms:        ["Rooms", "ルーム"],
  noRooms:      ["No rooms yet. Create one!", "まだルームがありません。つくってみよう！"],
  createRoomBtn:["➕ Create Room", "➕ ルームをつくる"],
  createRoomH:  ["Create a room", "ルームをつくる"],
  roomName:     ["Room name (up to 30 characters)", "ルームの名前（30文字まで）"],
  roomPw:       ["Password (optional, 6–20 characters)", "パスワード（なくてもOK・6〜20文字）"],
  createBtn:    ["CREATE ROOM", "ルームをつくる"],
  back:         ["Back", "もどる"],
  cancel:       ["Cancel", "キャンセル"],
  joinPw:       ["Room password", "ルームのパスワード"],
  joinBtn:      ["JOIN ROOM", "ルームに入る"],
  created:      ["🎉 ROOM CREATED!", "🎉 ルームができました！"],
  createdNote:  ["Tell your friends the room name and this password. It can't be shown again after you leave.", "ルームの名前とパスワードをともだちに教えてね。ルームを出ると、もう見られません。"],
  passwordIs:   ["Password:", "パスワード："],
  show:         ["Show", "見る"],
  hide:         ["Hide", "かくす"],
  hostIs:       ["Host: {name}", "ホスト：{name}"],
  stWaiting:    ["Waiting", "まっています"],
  stStarting:   ["Starting", "スタート中"],
  stRacing:     ["Racing", "レース中"],
  stFinished:   ["Finished", "おわり"],
  stFull:       ["Full", "まんいん"],
  // ---- lobby / host setup
  racers:       ["Racers", "レーサー"],
  waitingFor:   ["Waiting for players...", "ともだちを まっています…"],
  seatsFull:    ["All 35 seats are taken!", "35席ぜんぶ うまりました！"],
  tagHostRacer: ["HOST · RACER", "ホスト・レーサー"],
  tagHost:      ["HOST", "ホスト"],
  tagRacer:     ["RACER", "レーサー"],
  tagSpectator: ["SPECTATOR", "見る人"],
  hostSetup:    ["Host setup", "ホストのせってい"],
  textbook:     ["Textbook", "教科書"],
  units:        ["Units (choose 1–4)", "ユニット（1〜4つえらぶ）"],
  unitWords:    ["{n} words", "{n}語"],
  gameMode:     ["Game mode", "ゲームのしゅるい"],
  comingSoon:   ["coming soon", "じゅんびちゅう"],
  questions:    ["Questions:", "もんだい数："],
  hostJoin:     ["Host Join Race: {state}", "ホストもレースに さんか：{state}"],
  hostJoinNote: ["ON = you race and use one of the 35 seats. OFF = you only control the room.", "ON＝ホストもレースします（35席のうち1席）。OFF＝ルームの かんりだけ します。"],
  start:        ["START GAME", "ゲームスタート"],
  starting:     ["STARTING...", "スタート中…"],
  poolOk:       ["✅ {n} words available (40 are used per race). {r} racer(s) ready.", "✅ 使える単語は{n}語（レースでは40語）。レーサー{r}人 じゅんびOK。"],
  poolWait:     ["✅ {n} words available. Waiting for at least {m} racer(s).", "✅ 使える単語は{n}語。レーサーが{m}人以上 そろうのを まっています。"],
  poolShort:    ["❌ Only {n} usable words in your selection, but 40 are needed. Please select another unit.", "❌ 使える単語が{n}語しかありません（40語 ひつよう）。ほかのユニットも えらんでください。"],
  poolNone:     ["Choose at least one unit (up to 4).", "ユニットを1つ以上 えらんでください（4つまで）。"],
  poolLoading:  ["Loading the word list...", "たんごリストを よみこみ中…"],
  poolError:    ["❌ Couldn't load the word list. Check your connection; it will try again.", "❌ たんごリストを よみこめません。つながりを たしかめてね。もう一度 ためします。"],
  hostChoice:   ["The host's choice", "ホストが えらんだゲーム"],
  hostChoosing: ["The host is choosing a game...", "ホストが ゲームを えらんでいます…"],
  hostStarting: ["The host is starting the game...", "ホストが ゲームを はじめます…"],
  statusWaiting:["Waiting for players", "ともだちを まっています"],
  statusRace:   ["Race in progress", "レース中です"],
  statusDone:   ["Race finished", "レースが おわりました"],
  remove:       ["Remove", "はずす"],
  leave:        ["Leave room", "ルームを出る"],
  // ---- race
  raceH:        ["🏁 Race", "🏁 レース"],
  startsIn:     ["Starting in {n}...", "スタートまで {n}…"],
  go:           ["GO!", "スタート！"],
  raceOver:     ["🏁 Race finished", "🏁 レースしゅうりょう"],
  question:     ["Question {n}/40 · solved {s}", "もんだい {n}/40 ・ せいかい {s}"],
  whichWord:    ["What is the English word?", "英語は どれ？"],
  askJa:        ["What does it mean in Japanese?", "日本語の いみは どれ？"],
  modeUnsupported:["⚠️ This page doesn't know the host's game mode. Please reload the page.", "⚠️ このページは ホストの ゲームの しゅるいを しりません。ページを 再読み込みしてください。"],
  correct:      ["✅ Correct!", "✅ せいかい！"],
  tryAgain:     ["Not quite. Try again!", "おしい！ もう一度 チャレンジ！"],
  skip:         ["SKIP", "スキップ"],
  finishedWait: ["🎉 You finished! Waiting for the others...", "🎉 ゴール！ ほかの人を まっています…"],
  watching:     ["You are watching this race.", "レースを 見ています。"],
  liveBoard:    ["Live board", "リアルタイム ランキング"],
  offline:      ["Disconnected", "オフライン"],
  removed:      ["Removed", "はずされました"],
  game:         ["Game", "ゲームの内容"],
  checking:     ["Checking the word list...", "たんごリストを かくにん中…"],
  verifyOk:     ["✅ Your word list matches the host's (40 words verified).", "✅ ホストと おなじ単語リストです（40語かくにんずみ）。"],
  verifyBad:    ["⚠️ Your word list doesn't match the host's. Please reload the page.", "⚠️ ホストと単語リストが ちがいます。ページを 再読み込みしてください。"],
  verifyFail:   ["⚠️ Couldn't check the word list.", "⚠️ たんごリストを かくにんできませんでした。"],
  endRace:      ["END RACE", "レースをおわる"],
  backLobby:    ["BACK TO LOBBY", "ロビーにもどる"],
  hostAway:     ["The host is away. The room returns to the lobby soon, and the next player in order becomes host.", "ホストがいません。もうすぐロビーにもどり、じゅんばんで次の人がホストになります。"],
  // ---- results / review / projector (Phase D)
  results:      ["🏆 Results", "🏆 けっか"],
  fullRank:     ["Full rankings", "全員のランキング"],
  yourResult:   ["Your result", "あなたの けっか"],
  youCame:      ["You came {place} in {time}", "あなたは {n}位（{time}）"],
  dnf:          ["Did not finish ({s}/40)", "ゴールできず（{s}/40）"],
  place1:       ["1st", "1位"], place2: ["2nd", "2位"], place3: ["3rd", "3位"],
  review:       ["Words to Review", "ふくしゅうする たんご"],
  reviewWrong:  ["Wrong answers", "まちがえた たんご"],
  reviewSkip:   ["Skipped", "スキップした たんご"],
  reviewNone:   ["Nice! No words to review.", "すごい！ ふくしゅうする たんごは ありません。"],
  reviewLocal:  ["This list is only on your device.", "このリストは あなたの 端末だけに あります。"],
  again:        ["PLAY AGAIN (same settings)", "もう一回！（おなじせってい）"],
  projector:    ["Projector view", "大きい画面（プロジェクター）"],
  projectorOff: ["Exit projector view", "もどる"],
  soundOn:      ["Sound: ON", "おと：ON"], soundOff: ["Sound: OFF", "おと：OFF"],
  vibOn:        ["Vibration: ON", "バイブ：ON"], vibOff: ["Vibration: OFF", "バイブ：OFF"],
  confirmQ:     ["Remove {name} from the room?", "{name}さんを ルームから はずしますか？"],
  confirmNote:  ["{name} will be taken out of the room.", "{name}さんは ルームから はずされます。"],
  confirmYes:   ["Remove", "はずす"],
  confirmNo:    ["Cancel", "やめる"],
  nickBlocked:  ["That nickname isn't allowed. Please choose another one.", "そのニックネームは つかえません。ほかの名前に してください。"],
  nickChars:    ["Please use letters, numbers or spaces only (no links or symbols).", "文字・数字・スペースだけ つかえます（リンクや記号は ×）。"],
  roomBlocked:  ["That room name isn't allowed. Please choose another one.", "そのルームの名前は つかえません。ほかの名前に してください。"],
  roomChars:    ["Please use letters, numbers, spaces and simple marks only.", "文字・数字・スペース・かんたんな記号だけ つかえます。"],
  youWereRemoved:["The host removed you from the room.", "ホストに ルームから はずされました。"],
  // ---- messages
  inProgress:   ["A race is already in progress. You can join the next one.", "レースが はじまっています。次のレースに さんかしてね。"],
  roomFull:     ["This room is full (35/35).", "このルームは まんいんです（35/35）。"],
  roomGone:     ["That room is gone.", "そのルームは なくなりました。"],
  needNick:     ["Please enter a nickname (1–20 characters).", "ニックネームを 入れてください（1〜20文字）。"],
  needRoom:     ["Please enter a room name (1–30 characters).", "ルームの名前を 入れてください（1〜30文字）。"],
  pwLength:     ["The password must be 6–20 characters (or leave it empty).", "パスワードは 6〜20文字です（なくてもOK）。"],
  joinFailPw:   ["Couldn't join. Wrong password, or the room just filled up.", "入れませんでした。パスワードが ちがうか、ルームが まんいんです。"],
  joinFail:     ["Couldn't join. The room may be full or closed.", "入れませんでした。まんいんか、しめきられています。"],
  createFail:   ["Couldn't create a room. Please try again in a moment.", "ルームを つくれませんでした。しばらくして もう一度 ためしてください。"],
  startChanged: ["Couldn't start: the room changed. Please try again.", "スタートできませんでした。もう一度 ためしてください。"],
  startFail:    ["Couldn't start the game. Please try again.", "ゲームを はじめられませんでした。もう一度 ためしてください。"],
  nobodyRacing: ["Nobody is racing yet. Wait for at least {m} racer(s).", "まだ レーサーが いません。{m}人以上 まってね。"],
  modeSoon:     ["That game mode is coming soon.", "そのゲームは じゅんびちゅうです。"],
  hostSeatsFull:["All 35 racer seats are taken, so the host can't race.", "35席ぜんぶ うまっているので、ホストは レースに さんかできません。"],
  otherTab:     ["This room is already open in another tab. Please use that tab (or close it first).", "このルームは 別のタブで 開かれています。そちらを つかうか、先に とじてください。"],
  notConnected: ["Not connected yet. Please wait a moment and try again.", "まだ つながっていません。少し まってから もう一度。"],
  lostRoom:     ["Lost connection to the room.", "ルームとの つながりが きれました。"],
  lostRace:     ["You were disconnected and the race has already started.", "せつだんされている間に レースが はじまりました。"],
  roomUnavailable:["The room is no longer available.", "このルームは もう つかえません。"],
  roomFilled:   ["The room filled up while you were disconnected.", "つながっていない間に ルームが まんいんになりました。"],
  rejoinFail:   ["Couldn't rejoin the room.", "ルームに もどれませんでした。"],
  joinAgain:    ["You were disconnected from the room. Please join again.", "ルームから きれました。もう一度 入ってください。"],
  wrong:        ["Something went wrong. Please try again.", "うまくいきませんでした。もう一度 ためしてください。"],
  noServer:     ["Couldn't connect to Firebase. Please check the setup and try again.", "サーバーに つながりません。せっていを たしかめて、もう一度 ためしてください。"],
  roomListFail: ["Couldn't load the room list.", "ルームの一覧を よみこめません。"],
  wordsNotLoaded:["The word list isn't loaded yet.", "たんごリストが まだ よみこまれていません。"],
  chooseUnits:  ["Choose 1 to 4 units.", "ユニットを 1〜4つ えらんでください。"],
  tooFewWords:  ["Only {n} usable words. Please select another unit.", "使える単語が {n}語 しかありません。ほかのユニットも えらんでください。"],
  playAgainFail:["Couldn't start the next race. Please try again.", "次のレースを はじめられませんでした。もう一度 ためしてください。"]
};

export const ordinalKey = n => (n >= 1 && n <= 3 ? "place" + n : null);
export const ordinalEn = n => { const s = ["th", "st", "nd", "rd"], v = n % 100; return n + (s[(v - 20) % 10] || s[v] || s[0]); };
// -> { en, ja } with the {values} filled in
export function t(key, vars = {}) {
  const e = S[key]; if (!e) throw new Error("missing string: " + key);
  const fill = s => s.replace(/\{(\w+)\}/g, (_, k) => (k in vars ? String(vars[k]) : "{" + k + "}"));
  return { en: fill(e[0]), ja: fill(e[1]) };
}

// Japanese names of the game modes (the English names come from vocab.js).
export const MODE_JA = {
  "jp2en-choice4": "日本語→英語（4択）",
  "en2jp-choice4": "英語→日本語（4択）",
  "mixed-choice4": "ミックス（4択）",
  "spelling": "スペリング（入力）",
  "matching": "マッチング"
};
export const questionsJa = n => n + "問";
